/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Aufgabe1;


import java.util.LinkedList;

public class MainApp {

    public static void main(String[] args) {

        CommandFactory cmdFactory = new CommandFactory();
        Console con = new Console();

        // Linked list mit allen commands
        LinkedList<ICommand> commands = new LinkedList<>();
        commands.add(cmdFactory.createGCDSubReCmd());
        commands.add(cmdFactory.createGCDSubItCmd());
        commands.add(cmdFactory.createGCDDivRestRecCmd());
        commands.add(cmdFactory.createGCDDivRestItCmd());
        commands.add(cmdFactory.SiebEratosthenes());
       do {
           //Menü wird angezeigt und ausgeführt
           int wahl = con.consoleMenue();
           if (wahl == 0) {
               System.exit(0);
           } else {
               ICommand command = commands.get(wahl - 1);
               //gewählter command wird angezeigt und ausgeführt
               System.out.println(command);
               command.execute();
               System.out.println();
           }
       }while(true);
    }
}
